import type { TaskItem } from "@/types/domain";

export const tasks: TaskItem[] = [
  {
    id: "task-1",
    title: "주간 보고서 초안 작성",
    status: "todo",
    priority: "high",
    scheduledDate: "2026-05-12",
    dueDate: "2026-05-12",
    deferredCount: 0,
    memo: "팀 공유 전 숫자 확인 필요",
  },
  {
    id: "task-2",
    title: "알고리즘 문제 3개 풀기",
    status: "inProgress",
    priority: "high",
    scheduledDate: "2026-05-12",
    dueDate: "2026-05-14",
    deferredCount: 2,
  },
  {
    id: "task-3",
    title: "영어 단어 50개 복습",
    status: "todo",
    priority: "low",
    scheduledDate: "2026-05-13",
    dueDate: "2026-05-20",
    deferredCount: 1,
  },
  {
    id: "task-4",
    title: "포트폴리오 프로젝트 README 정리",
    status: "inProgress",
    priority: "normal",
    scheduledDate: "2026-05-11",
    dueDate: "2026-05-12",
    deferredCount: 3,
    memo: "스크린샷 최신화",
  },
  {
    id: "task-5",
    title: "비타민 챙겨먹기",
    status: "done",
    priority: "normal",
    scheduledDate: "2026-05-12",
    completedAt: "2026-05-12T08:20:00",
    deferredCount: 0,
  },
  {
    id: "task-6",
    title: "면접 질문 10개 답변 정리",
    status: "todo",
    priority: "high",
    scheduledDate: "2026-05-15",
    dueDate: "2026-05-13",
    deferredCount: 4,
    memo: "마감일을 넘긴 예정일 테스트",
  },
];
